version: '3.9'

services:
  python:
    image: akraradets/ait-ml-python:2023
    build: 
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./:/code
  mlflow:
    image: akraradets/ait-ml-mlflow:2023
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]